"""Extract complete IL2CPP profiles from the pinned ASR source.

Usage: python scripts/import-il2cpp-profiles.py PATH_TO_ASR_CHECKOUT [--check]
Updates the checked-in JSON catalog and generated standard-library regions.
The generated constructors are separate functions so explicit selection need
not retain automatic lookup.
"""
import json
from pathlib import Path
import re
import subprocess
import sys

PIN = "cf732d3aeac7509c8ab5f29a4d0d28f16487d245"
ROOT = Path(__file__).resolve().parents[1]
ASR = Path(sys.argv[1]).resolve()
GIT = ["git", "-c", f"safe.directory={ASR.as_posix()}", "-C", str(ASR)]
revision = subprocess.check_output([*GIT, "rev-parse", "HEAD"], text=True).strip()
if revision != PIN:
    raise SystemExit(f"Expected ASR {PIN}, found {revision}")
paths = [f"src/game_engine/unity/il2cpp/{name}.rs" for name in ["builds", "profiles"]]
if subprocess.check_output([*GIT, "diff", "HEAD", "--", *paths], text=True):
    raise SystemExit("The pinned IL2CPP source files have uncommitted changes")

FIELDS = [
    ("assembly.image", "assemblyImage", False),
    ("assembly.name", "assemblyName", True),
    ("image.assembly_name", "imageAssemblyName", True),
    ("image.type_count", "imageTypeCount", False),
    ("image.type_start", "imageTypeStart", False),
    ("class.name", "className", False),
    ("class.namespace", "classNamespace", False),
    ("class.declaring_type", "classDeclaring", True),
    ("class.parent", "classParent", False),
    ("class.fields", "classFields", False),
    ("class.static_fields", "classStatics", False),
    ("class.instance_size", "classInstanceSize", True),
    ("class.field_count", "classFieldCount", False),
    ("generic.cached_class", "genericCachedClass", True),
    ("type_.data", "typeData", True),
    ("type_.kind", "typeKind", True),
    ("field.name", "fieldName", False),
    ("field.type_", "fieldType", True),
    ("field.offset", "fieldValue", False),
    ("field.size", "fieldStride", False),
]


def offsets(body):
    result = {}
    for group, contents in re.findall(r"(\w+):\s*\w+\s*\{([^{}]*)\}", body):
        for member, value in re.findall(
            r"(\w+):\s*(TypeStart::(?:Inline|Handle)\(0x[\da-fA-F]+\)|"
            r"Some\(0x[\da-fA-F]+\)|None|0x[\da-fA-F]+)\s*,", contents
        ):
            if value.startswith("TypeStart::"):
                mode, at = re.fullmatch(r"TypeStart::(\w+)\(([^)]+)\)", value).groups()
                value = {"kind": mode, "offset": int(at, 0)}
            else:
                value = None if value == "None" else int(value.removeprefix("Some(").removesuffix(")"), 0)
            result[f"{group}.{member}"] = value
    assert set(result) == {field[0] for field in FIELDS}, result.keys()
    return result


source = (ASR / paths[0]).read_text(encoding="utf-8").split("#[cfg(test)]")[0]
names = (ASR / paths[1]).read_text(encoding="utf-8").split("#[cfg(")[0]
names = {int(index): name for name, index in re.findall(r"(UNITY_\w+) = (\d+);", names)}
builds = []
for match in re.finditer(
    r"Build \{\s*unity: \(([^)]+)\),\s*profile: Profile \{\s*"
    r"pointer_size: PointerSize::Bit(32|64),(.*?)\n        \},\n    \}", source, re.S
):
    version, width, body = match.groups()
    name = names[len(builds)]
    parts = name.removeprefix("UNITY_").split("_")
    architecture = "X64" if parts[-2:] == ["X86", "64"] else "X86"
    player = "_".join(parts[:-2] if architecture == "X64" else parts[:-1]).lower()
    builds.append(dict(name=name, method=f"unity{player}{architecture}",
                       version=[int(n.strip()) for n in version.split(",")],
                       width=int(width), offsets=offsets(body)))
assert len(builds) == len(names) == 22
assert len({tuple(row["version"]) for row in builds}) == 11
assert len({(tuple(row["version"]), row["width"]) for row in builds}) == 22

output = ROOT / "target/imported-il2cpp"
output.mkdir(parents=True, exist_ok=True)
(output / "profiles.json").write_text(json.dumps(dict(asr_revision=PIN,
    builds=builds), indent=2) + "\n", encoding="utf-8")
lines = [f"// ASR {PIN}.",
         "// Generated by scripts/import-il2cpp-profiles.py."]
for row in builds:
    lines += ["", f"    /// Measured {row['name']}; player file version {'.'.join(map(str, row['version']))}.",
              "    ///", "    /// Returns the complete layout measured from this player's GameAssembly PDB.",
              "    ///", "    /// # Example", "    ///", "    /// Select this measured layout", "    ///",
              "    /// ```splitscript", f"    /// let measured = Il2CppProfile.{row['method']}()", "    /// ```",
              f"    static fn {row['method']}() -> Il2CppProfile {{", "        return Il2CppProfile {",
              f"            pointerSize: PointerSize.Bit{row['width']},"]
    for source, name, optional in FIELDS:
        value = row["offsets"][source]
        if isinstance(value, dict):
            value = f"Il2CppTypeStart.{value['kind'].lower()}({hex(value['offset'])})"
        else:
            value = "None" if value is None else f"Some({hex(value)})" if optional else hex(value)
        lines += [f"            {name}: {value},"]
    lines += ["        }", "    }"]
(output / "constructors.split").write_text("\n".join(lines) + "\n", encoding="utf-8")
header = [
    "/// Describes where an IL2CPP image stores its first type index.",
    "///", "/// # Example", "///", "/// Select an indirect type index", "///",
    "/// ```splitscript", "/// let start = Il2CppTypeStart.handle(0x28)", "/// ```",
    "@representation(gcStruct, nullable)",
    "@valueUsage(structField, enumPayload, stateField, localVariable, globalVariable)",
    "struct Il2CppTypeStart {",
    "    /// Byte offset in the image.", "    private offset: u64,",
    "    /// Whether the image member points to the index.", "    private indirect: bool,",
]
for mode in ["inline", "handle"]:
    header += [f"    /// The image stores {'the index directly' if mode == 'inline' else 'a pointer to the index'} at this offset.",
               "    ///", "    /// Type indices are four-byte integers, independent of the pointer width.",
               "    ///", "    /// # Example", "    ///", "    /// Describe the image member", "    ///",
               "    /// ```splitscript", f"    /// let start = Il2CppTypeStart.{mode}(0x18)", "    /// ```",
               f"    static fn {mode}(", "        /// Offset from the image address.", "        offset: u64,",
               "    ) -> Il2CppTypeStart {",
               f"        return Il2CppTypeStart {{ offset, indirect: {'true' if mode == 'handle' else 'false'} }}", "    }"]
header += ["}", "", "/// A complete measured or custom IL2CPP memory layout.",
           "///", "/// All members are required when constructing a custom profile. Unknown optional",
           "/// metadata facts must be written as None; they are never borrowed from another build.",
           "///", "/// # Example", "///", "/// Choose a measured player layout", "///",
           "/// ```splitscript", "/// let profile = Il2CppProfile.unity2021_3_11f1X64()", "/// ```",
           "@representation(gcStruct, nullable)",
           "@valueUsage(structField, enumPayload, stateField, localVariable, globalVariable)",
           "struct Il2CppProfile {"]
for source, name, optional in [("pointer width", "pointerSize", False), *FIELDS]:
    ty = "PointerSize" if name == "pointerSize" else "Il2CppTypeStart" if name == "imageTypeStart" else "u64?" if optional else "u64"
    description = "Target pointer width." if name == "pointerSize" else "Location and storage mode of the image's first type index." if name == "imageTypeStart" else f"Target byte {'stride' if name == 'fieldStride' else 'offset'} for `{source}`."
    if optional:
        description += " None means this fact is unavailable."
    header += [f"    /// {description}", "    ///", "    /// # Example", "    ///",
               "    /// Inspect a measured layout fact", "    ///", "    /// ```splitscript",
               "    /// let profile = Il2CppProfile.unity2021_3_11f1X64()",
               f"    /// let fact = profile.{name}", "    /// ```", f"    {name}: {ty},", ""]
header += ["    // BEGIN GENERATED IL2CPP PROFILES", *lines, "    // END GENERATED IL2CPP PROFILES", "}"]
(output / "profile.split").write_text("\n".join(header) + "\n", encoding="utf-8")
selection = ["    // Exact four-component matches precede the major/minor fallback.",
             "    private static fn select(version: FileVersion, width: PointerSize) -> Il2CppProfile {"]


def choose(pair):
    x64 = next(row for row in pair if row["width"] == 64)
    x86 = next(row for row in pair if row["width"] == 32)
    return [
        "            if width == PointerSize.Bit64 {",
        f"                print(\"Unity IL2CPP: selected {x64['name']}\")",
        f"                return Il2CppProfile.{x64['method']}()",
        "            }",
        f"            print(\"Unity IL2CPP: selected {x86['name']}\")",
        f"            return Il2CppProfile.{x86['method']}()",
    ]


pairs = [builds[i:i + 2] for i in range(0, len(builds), 2)]
for pair in pairs:
    version = ".".join(map(str, pair[0]["version"]))
    selection += [f'        if version == v"{version}" {{', *choose(pair), "        }"]
seen = set()
for pair in reversed(pairs):
    major, minor, *_ = pair[0]["version"]
    if (major, minor) in seen:
        continue
    seen.add((major, minor))
    selection += [f"        if version.major > {major} || version.major == {major} && version.minor >= {minor} {{",
                  *choose(pair), "        }"]
selection += [line[4:] for line in choose(pairs[0])] + ["    }"]
(output / "selection.split").write_text("\n".join(selection) + "\n", encoding="utf-8")

def update(path, contents):
    if "--check" in sys.argv:
        if not path.exists() or path.read_text(encoding="utf-8") != contents:
            raise SystemExit(f"Generated IL2CPP profiles differ: {path}")
    else:
        path.write_text(contents, encoding="utf-8", newline="\n")


update(ROOT / "tests/fixtures/il2cpp-pe-profiles.json", (output / "profiles.json").read_text(encoding="utf-8"))
stdlib = ROOT / "stdlib/standard.split"
contents = stdlib.read_text(encoding="utf-8")
for region, generated in [("SELECTION", "selection.split"), ("PROFILES", "constructors.split")]:
    begin = f"    // BEGIN GENERATED IL2CPP {region}\n"
    end = f"    // END GENERATED IL2CPP {region}"
    start = contents.index(begin) + len(begin)
    stop = contents.index(end, start)
    contents = contents[:start] + (output / generated).read_text(encoding="utf-8") + contents[stop:]
update(stdlib, contents)
print(f"{'Checked' if '--check' in sys.argv else 'Imported'} {len(builds)} complete IL2CPP profiles")
